AllCops:
   Exclude:
      - 'app/channels/**/*'
      - 'app/jobs/*'
      - 'config/initializers/*'
      - 'config/boot.rb'
      - 'config/environment.rb'
      - 'config/puma.rb'
      - 'config/spring.rb'
      - 'db/migrate/*'
      - 'db/schema.rb'
      - 'db/seeds.rb'
      - 'node_modules/**/*'
   TargetRubyVersion: 2.4
   DisplayCopNames: true

Style/Documentation:
   Enabled: false

Style/AsciiComments:
   Enabled: false

Style/SymbolArray:
   EnforcedStyle: brackets

Style/RedundantReturn:
   Enabled: false

Style/WordArray:
   EnforcedStyle: brackets

Style/EmptyMethod:
   Enabled: false

Metrics/LineLength:
   Max:  90

Metrics/AbcSize:
   Max:  20

Layout/IndentationWidth:
   Width: 3
